import StrategySection from "components/homepage/StrategySection";
import Head from "next/head";
import Image from "next/image";
import HeroSection from "../components/homepage/HeroSection";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>PTS Holdings</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container space-y-[100px] overflow-hidden">
				<HeroSection />
				<StrategySection />
			</main>
		</div>
	);
}
